name: login_smart_factory
description: A new Flutter project.
version: 0.0.2
homepage:
publish_to: none

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ota_update: ^4.0.2
  url_launcher: ^6.1.6
  token_provider:
    git:
      url: https://github.com/mag1c-dev/token_provider
  download_install_apk:
    path: ../download_install_apk
  shared_preference_app_group: ^1.0.0+1
  android_intent_plus: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
